---

- name: Create application directory
  ansible.builtin.file:
    path: /opt/webtest
    state: directory
    mode: '0755'

- name: Deploy Docker Compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/webtest/docker-compose.yml
    mode: '0644'

- name: Start the Hello World application
  community.docker.docker_compose_v2:
    project_src: /opt/webtest
    state: present
    pull: always
